"use strict";
// prompt.id 0 is reserved for questions not related to rounds (like "What's your name?" etc.)
window.prompts = [
	{"id":"10", "prompt":"___ was my nickname in high school."},
	{"id":"11", "prompt":"___ was my band name in high school."},
	{"id":"12", "prompt":"That's why they call me Johnny ___."},
	{"id":"13", "prompt":"What's a bad name for a child?"},
	{"id":"14", "prompt":"What's the best superpower?"},
	{"id":"15", "prompt":"On his deathbed, Otto von Bismarck apocryphally predicted that ___ would cause World War One."},
	{"id":"16", "prompt":"What is Garrison Keillor's personal hell?"},
	{"id":"17", "prompt":"What's a fun game to play during a road trip?"},
	{"id":"18", "prompt":"It was weird that grandpa kept ___"},
	{"id":"19", "prompt":"What's a good name for a superhero dog?"},
	{"id":"20", "prompt":"Critics are raving about the new children's cartoon about the Holocaust, ___"},
	{"id":"21", "prompt":"What's something you DON'T want to hear your doctor say?"},
	{"id":"22", "prompt":"What's something you DON'T want to hear your surgeon say?"},
	{"id":"23", "prompt":"What's something you DON'T want to hear your spouse say?"},
	{"id":"24", "prompt":"What's something you DON'T want to hear your gynocologist say?"},
	{"id":"25", "prompt":"What's something you DON'T want to hear your obstetrician say?"},
	{"id":"26", "prompt":"What's something you DON'T want to hear your veternarian say?"},
	{"id":"27", "prompt":"What's something you DON'T want to hear your optometrists say?"},
	{"id":"28", "prompt":"What's something you DON'T want to hear your dentist say?"},
	{"id":"29", "prompt":"What's something you DON'T want to hear your son say?"},
	{"id":"30", "prompt":"What's something you DON'T want to hear your daughter say?"},
	{"id":"31", "prompt":"What's something you DON'T want to hear your dad say?"},
	{"id":"32", "prompt":"What's something you DON'T want to hear your mom say?"},
	{"id":"33", "prompt":"If they renamed Washington state, what would they rename it too?"},
	{"id":"34", "prompt":"The hot new dance craze sweeping the nation: The __"},
	{"id":"35", "prompt":"Worst reason to be called to the principal's office in high school."},
	{"id":"36", "prompt":"Best reason to be called to the principal's office in high school."},
	{"id":"37", "prompt":"Name something you can use in place of a taco shell, in a pinch."},
	{"id":"38", "prompt":"Type the funniest word you can think of."},
	{"id":"39", "prompt":"Write something that you shouldn't ask at a funeral."},
	{"id":"40", "prompt":"What's a bad name for a band?"},
	{"id":"41", "prompt":"What's a bad name for a law firm?"},
	{"id":"42", "prompt":"Birds of a feather flock together, fish of a fin __"},
	{"id":"43", "prompt":"Complete the analogy: a puddle is to the ocean as __"},
	{"id":"44", "prompt":"By what method would you like your death to be avenged?"},
	{"id":"45", "prompt":"What's a film that should never be made?"},
	{"id":"46", "prompt":"Oh, just write something obscene."},
	{"id":"47", "prompt":"What's the most important trait you look for in a partner?"},
	{"id":"48", "prompt":"What's a good name for a water park?"},
	{"id":"49", "prompt":"What's a good name for a city populated entirely by birds?"},
	{"id":"50", "prompt":"What's your social security number? You can trust me... I'm Quiplibre..."},
	{"id":"51", "prompt":"What's a group of people it will always be ok to make fun of?"},
	{"id":"52", "prompt":"Who REALLY shot JFK?"},
	{"id":"53", "prompt":"Not only is Bigfoot real, he also has an adorable pet panda named __"},
	{"id":"54", "prompt":"My name is Ozymandias, king of kings: Look on my works, ye Mighty, and __!"},
	{"id":"55", "prompt":"What's a good idea for a mad scientist's high school science fair project?"},
	{"id":"56", "prompt":"What's a weird way to find out your spouse is cheating on you?"},
	{"id":"57", "prompt":"What's the first sign that your dog is actually a wild animal?"},
	{"id":"58", "prompt":"Make up a name for a new breed of dog."},
	{"id":"59", "prompt":"'The Holy Ghost' is a translation error. The real holy trinity is comprised of the Father, the Son, and __"},
	{"id":"60", "prompt":"The murderer is in this very room! The murderer is one of you! THE MURDERER IS ___"}
]
